name: Deploy react app
on:
  push:
    branches:
    - main
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/chechout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install packages
        run: npm install
      - name: reistry github user
        run: /
          git config --global user.email bycrisgd@gmail.com
          git config --global user.name "uzbuzbiz"
      - name: deploy the app
        run: npm run deploy
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}